#####################################################################
#       Setting dont_touch and dont_use preserve setting             
#####################################################################

set_db base_cell:HS65_GS_BK1SX1 .dont_use true
set_db base_cell:HS65_GS_BK1X1 .dont_use true
set_db base_cell:HS65_GS_DFPHQNX18 .dont_use true
set_db base_cell:HS65_GS_DFPHQNX27 .dont_use true
set_db base_cell:HS65_GS_DFPHQNX35 .dont_use true
set_db base_cell:HS65_GS_DFPHQX18 .dont_use true
set_db base_cell:HS65_GS_DFPHQX27 .dont_use true
set_db base_cell:HS65_GS_DFPHQX35 .dont_use true
set_db base_cell:HS65_GS_DFPQNX18 .dont_use true
set_db base_cell:HS65_GS_DFPQNX27 .dont_use true
set_db base_cell:HS65_GS_DFPQNX35 .dont_use true
set_db base_cell:HS65_GS_DFPQX18 .dont_use true
set_db base_cell:HS65_GS_DFPQX27 .dont_use true
set_db base_cell:HS65_GS_DFPQX35 .dont_use true
set_db base_cell:HS65_GS_DFPRQNX18 .dont_use true
set_db base_cell:HS65_GS_DFPRQNX27 .dont_use true
set_db base_cell:HS65_GS_DFPRQNX35 .dont_use true
set_db base_cell:HS65_GS_DFPRQX18 .dont_use true
set_db base_cell:HS65_GS_DFPRQX27 .dont_use true
set_db base_cell:HS65_GS_DFPRQX35 .dont_use true
set_db base_cell:HS65_GS_DFPSQNX18 .dont_use true
set_db base_cell:HS65_GS_DFPSQNX27 .dont_use true
set_db base_cell:HS65_GS_DFPSQNX35 .dont_use true
set_db base_cell:HS65_GS_DFPSQX18 .dont_use true
set_db base_cell:HS65_GS_DFPSQX27 .dont_use true
set_db base_cell:HS65_GS_DFPSQX35 .dont_use true
set_db base_cell:HS65_GS_SDFPBTQX9 .dont_use true
set_db base_cell:HS65_GS_SDFPHQNTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPHQNTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPHQNTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPHQNX18 .dont_use true
set_db base_cell:HS65_GS_SDFPHQNX27 .dont_use true
set_db base_cell:HS65_GS_SDFPHQNX35 .dont_use true
set_db base_cell:HS65_GS_SDFPHQTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPHQTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPHQTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPHQX18 .dont_use true
set_db base_cell:HS65_GS_SDFPHQX27 .dont_use true
set_db base_cell:HS65_GS_SDFPHQX35 .dont_use true
set_db base_cell:HS65_GS_SDFPHRQNTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPHRQNTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPHRQNTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPHRQTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPHRQTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPHRQTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPQNTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPQNTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPQNTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPQNX18 .dont_use true
set_db base_cell:HS65_GS_SDFPQNX27 .dont_use true
set_db base_cell:HS65_GS_SDFPQNX35 .dont_use true
set_db base_cell:HS65_GS_SDFPQTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPQTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPQTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPQX18 .dont_use true
set_db base_cell:HS65_GS_SDFPQX27 .dont_use true
set_db base_cell:HS65_GS_SDFPQX35 .dont_use true
set_db base_cell:HS65_GS_SDFPRQNTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPRQNTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPRQNTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPRQNX18 .dont_use true
set_db base_cell:HS65_GS_SDFPRQNX27 .dont_use true
set_db base_cell:HS65_GS_SDFPRQNX35 .dont_use true
set_db base_cell:HS65_GS_SDFPRQTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPRQTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPRQTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPRQX18 .dont_use true
set_db base_cell:HS65_GS_SDFPRQX27 .dont_use true
set_db base_cell:HS65_GS_SDFPRQX35 .dont_use true
set_db base_cell:HS65_GS_SDFPSQNTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPSQNTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPSQNTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPSQNX18 .dont_use true
set_db base_cell:HS65_GS_SDFPSQNX27 .dont_use true
set_db base_cell:HS65_GS_SDFPSQNX35 .dont_use true
set_db base_cell:HS65_GS_SDFPSQTX18 .dont_use true
set_db base_cell:HS65_GS_SDFPSQTX27 .dont_use true
set_db base_cell:HS65_GS_SDFPSQTX35 .dont_use true
set_db base_cell:HS65_GS_SDFPSQX18 .dont_use true
set_db base_cell:HS65_GS_SDFPSQX27 .dont_use true
set_db base_cell:HS65_GS_SDFPSQX35 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX10 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX14 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX17 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX21 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX24 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX27 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX31 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX34 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX38 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX41 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX52 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX62 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX7 .dont_use true
set_db base_cell:HS65_GSP_CNHLSX82 .dont_use true
set_db base_cell:HS65_GS_CAPX18 .dont_use true
set_db base_cell:HS65_GS_CAPX35 .dont_use true
set_db base_cell:HS65_GS_CAPX53 .dont_use true
set_db base_cell:HS65_GS_CAPX9 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_0 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_1 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_10 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_11 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_12 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_13 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_14 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_15 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_16 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_17 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_18 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_19 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_2 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_20 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_21 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_22 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_23 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_3 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_4 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_5 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_6 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_7 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_8 .dont_use true
set_db base_cell:HS65_GS_CNBFX38_9 .dont_use true
set_db base_cell:ANA_1V8_SF_2ROWS .dont_use true
set_db base_cell:ANA_1V8_SF_LIN .dont_use true
set_db base_cell:BD2SCARUDQP_1V8_SF_2ROWS .dont_use true
set_db base_cell:BD2SCARUDQP_1V8_SF_LIN .dont_use true
set_db base_cell:BD4SCARUDQP_1V8_SF_2ROWS .dont_use true
set_db base_cell:BD4SCARUDQP_1V8_SF_LIN .dont_use true
set_db base_cell:BD8SCARUDQP_1V8_SF_2ROWS .dont_use true
set_db base_cell:BD8SCARUDQP_1V8_SF_LIN .dont_use true


set_db base_cell:HS65_GS_BK1SX1 .dont_touch true
set_db base_cell:HS65_GS_BK1X1 .dont_touch true
set_db base_cell:HS65_GS_SDFPBTQX9 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX10 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX14 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX17 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX21 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX24 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX27 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX31 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX34 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX38 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX41 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX52 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX62 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX7 .dont_touch true
set_db base_cell:HS65_GSP_CNHLSX82 .dont_touch true
set_db base_cell:HS65_GS_CAPX18 .dont_touch true
set_db base_cell:HS65_GS_CAPX35 .dont_touch true
set_db base_cell:HS65_GS_CAPX53 .dont_touch true
set_db base_cell:HS65_GS_CAPX9 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_0 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_1 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_10 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_11 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_12 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_13 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_14 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_15 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_16 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_17 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_18 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_19 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_2 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_20 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_21 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_22 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_23 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_3 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_4 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_5 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_6 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_7 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_8 .dont_touch true
set_db base_cell:HS65_GS_CNBFX38_9 .dont_touch true
set_db base_cell:ANA_1V8_SF_2ROWS .dont_touch true
set_db base_cell:ANA_1V8_SF_LIN .dont_touch true
set_db base_cell:BD2SCARUDQP_1V8_SF_2ROWS .dont_touch true
set_db base_cell:BD2SCARUDQP_1V8_SF_LIN .dont_touch true
set_db base_cell:BD4SCARUDQP_1V8_SF_2ROWS .dont_touch true
set_db base_cell:BD4SCARUDQP_1V8_SF_LIN .dont_touch true
set_db base_cell:BD8SCARUDQP_1V8_SF_2ROWS .dont_touch true
set_db base_cell:BD8SCARUDQP_1V8_SF_LIN .dont_touch true
