##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Add filler cells to the design                         ##
##  -Generate a summary report of the final design          ##
##############################################################
##Add filler cells
add_fillers -base_cells HS65_GS_FILLERPFP4 HS65_GS_FILLERPFP3 HS65_GS_FILLERPFP2 HS65_GS_FILLERPFP1 -prefix FILLER
##Generate reports
report_summary -out_dir summaryReport
